name: ' Publish To AppSource'
run-name: 'Publish To AppSource - Version ${{ inputs.appVersion }}, Projects ${{ inputs.projects }}'

on:
  workflow_dispatch:
    inputs:
      appVersion:
        description: App version to deliver to AppSource (current, prerelease, draft, latest or version number)
        required: false
        default: 'current'
      projects:
        description: Projects to publish to AppSource if the repository is multi-project. Default is *, which will publish all projects to AppSource.
        required: false
        default: '*'
      GoLive:
        description: Promote AppSource App to go live if it passes technical validation?
        type: boolean
        default: false

permissions:
  actions: read
  contents: read
  id-token: write

defaults:
  run:
    shell: powershell

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}

jobs:
  Initialization:
    needs: [ ]
    runs-on: [ windows-2025 ]
    outputs:
      telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
    steps:
      - name: Dump Workflow Information
        uses: microsoft/AL-Go/Actions/DumpWorkflowInfo@d101244b872b091a8894c1ba4d58e5f0b652823e
        with:
          shell: powershell

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Initialize the workflow
        id: init
        uses: microsoft/AL-Go/Actions/WorkflowInitialize@d101244b872b091a8894c1ba4d58e5f0b652823e
        with:
          shell: powershell

  Deliver:
    needs: [ Initialization ]
    runs-on: [ windows-2025 ]
    name: Deliver to AppSource
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Read settings
        uses: microsoft/AL-Go/Actions/ReadSettings@d101244b872b091a8894c1ba4d58e5f0b652823e
        with:
          shell: powershell

      - name: Read secrets
        id: ReadSecrets
        uses: microsoft/AL-Go/Actions/ReadSecrets@d101244b872b091a8894c1ba4d58e5f0b652823e
        with:
          shell: powershell
          gitHubSecrets: ${{ toJson(secrets) }}
          getSecrets: 'appSourceContext'

      - name: Deliver
        uses: microsoft/AL-Go/Actions/Deliver@d101244b872b091a8894c1ba4d58e5f0b652823e
        env:
          Secrets: '${{ steps.ReadSecrets.outputs.Secrets }}'
        with:
          shell: powershell
          type: 'Release'
          projects: ${{ github.event.inputs.projects }}
          deliveryTarget: 'AppSource'
          artifacts: ${{ github.event.inputs.appVersion }}
          goLive: ${{ github.event.inputs.goLive }}

  PostProcess:
    needs: [ Initialization, Deliver ]
    if: always()
    runs-on: [ windows-2025 ]
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Finalize the workflow
        id: PostProcess
        uses: microsoft/AL-Go/Actions/WorkflowPostProcess@d101244b872b091a8894c1ba4d58e5f0b652823e
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          shell: powershell
          telemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}
          currentJobContext: ${{ toJson(job) }}
